os: linux

language: node_js
node_js: stable

before_install:
  - npm install -g vsce
install:
  - npm install
script:
  - vsce package

deploy:
- provider: releases
  skip_cleanup: true
  api_key: [GITHUB_AUTH_TOKEN]
  name: Release $TRAVIS_TAG
  draft: true
  file_glob: true
  file: "*.vsix"
  on:
    tags: true
- provider: script
  skip_cleanup: true
  script: vsce publish -p $VS_TOKEN
  on:
    tags: true